version: 2

models:
  - name: factLeave
    description: "Fact table for employee leave data"
    columns:
      - name: employeeid
        description: "Foreign key to the employee dimension table"
        tests:
          - not_null
          - relationships:
              to: ref('dimEmployee')
              field: employeeid

      - name: department_sk
        description: "Foreign key to the department dimension table"
        tests:
          - not_null
          - relationships:
              to: ref('dimDepartment')
              field: department_sk

      - name: leavetype_sk
        description: "Foreign key to the leave type dimension table"
        tests:
          - not_null
          - relationships:
              to: ref('dimLeaveType')
              field: leavetype_sk

      - name: region_sk
        description: "Foreign key to the region dimension table"
        tests:
          - not_null
          - relationships:
              to: ref('dimRegion')
              field: region_sk

      - name: shift_sk
        description: "Foreign key to the shift dimension table"
        tests:
          - not_null
          - relationships:
              to: ref('dimShift')
              field: shift_sk