
models:
  - name: factLeave
    description: "Fact table for employee leave data"
    columns:
      - name: employee_sk
        description: "FK to employee"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimEmployee')
                field: employeeid

      - name: department_sk
        description: "FK to department"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimDepartment')
                field: department_sk

      - name: leavetype_sk
        description: "FK to leave type"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimLeaveType')
                field: leavetype_sk

      - name: region_sk
        description: "FK to region"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimRegion')
                field: region_sk

      - name: shift_sk
        description: "FK to shift"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimShift')
                field: shift_sk


  - name: dimDepartment
    description: "Dimension table for departments in the gold schema"
    columns:
      - name: department_sk
        description: "Surrogate key for the department, generated from departmentid"
        tests:
          - unique:
              description: "Ensures department_sk is unique across all records"
          - not_null:
              description: "Ensures department_sk is not null"

      - name: departmentid
        description: "Natural key for the department from the source system"
        tests:
          - not_null:
              description: "Ensures departmentid is not null"
          - unique:
              description: "Ensures departmentid is unique across all records"

      - name: departmentname
        description: "Name of the department"
        tests:
          - not_null:
              description: "Ensures departmentname is not null"

      - name: groupname
        description: "Group or category the department belongs to"
        tests:
          - not_null:
              description: "Ensures groupname is not null"