
models:
  - name: factLeave
    description: "Fact table for employee leave data"
    columns:
      - name: employeeid
        description: "FK to employee"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimEmployee')
                field: employeeid

      - name: department_sk
        description: "FK to department"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimDepartment')
                field: department_sk

      - name: leavetype_sk
        description: "FK to leave type"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimLeaveType')
                field: leavetype_sk

      - name: region_sk
        description: "FK to region"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimRegion')
                field: region_sk

      - name: shift_sk
        description: "FK to shift"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dimShift')
                field: shift_sk
