sources:
  - name: adventureworks
    database: "{{ var('adventureworks_db') }}"
    schema: HUMANRESOURCES
    tables:
      - name: employee
      - name: EMPLOYEEDEPARTMENTHISTORY
      - name: department
      - name: shift